### PR TITLE
 add file rugiraprince md

### PR DESCRIPTION
**Pull request by rugiraprince**
- [x] I wrote my markdown locally on a new branch
- [x] My bio file is named _exactly_ the same as my GitHub username
- [x] My `bio` link in the class README opens to my student bio file
- [x] I pulled and merged `main` into my branch before pushing
- [x] I pushed my branch to the class repository and opened a PR
- [x] I went through the PR checklist
- [x] All the CI check pass
- [x] I assigned a coach to review my PR
- [x] I
      [linked my PR to this issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)

### CODE REVIEW

**Comment by rugiraprince** [comment]
hey @bermarte i tried now but i still have one faults can check for me ?

**Comment by bermarte** [comment]
Run again the scripts, `npm run format` and the rest. Tomorrow I will have a look at it.

**Review by bermarte — CHANGES_REQUESTED** [review]
Try again running the scripts.

**Comment by rugiraprince** [comment]
@bermarte now is good thank you

**Comment by rugiraprince** [comment]
@bermarte @samirm00 may you check before i merge it ?

**Review by denisrossi — APPROVED** [review]

**Pull request merged**
