### PR TITLE
rugiraprince.md

### PR DESCRIPTION
**Pull request by rugiraprince**
### General Checks

- [x] the branch is up to date with `main`/`master`
- [x] the code works when pulled and run locally
- [x] All CI checks pass
- [x] all conflicts are resolved (if any)
- [x] PR has a descriptive title
- [x] PR has appropriate labels and milestones for easy identification
- [x] PR it is assigned to the owner
- [x] reviewers are assigned
- [x] the PR contributes only one focused change
- [x] It is in the appropriate column in the project board (if necessary)
- [x] has short and clear description
- [x] is linked to an issue (if it is related)
- [x] feedback is addressed (if any and if it is appropriate feedback.)

### Markdown

- [x] the markdown source is formatted
- [x] spelling and grammar is correct in all text
- [x] The markdown looks correct when you preview the file
- [x] all links and images work
- [x] any embedded code snippets are formatted

### CODE REVIEW

**Review by samirm00 — COMMENTED** [review]
Please only add your changes to students-bios, you have modified `package.json` which you are not suppose to change at all.

**Comment by rugiraprince** [comment]
@samirm00 i get it so apart from what else can i do ? i don't know why its says all checks have failed??

**Comment by samirm00** [comment]
@rugiraprince you have many header 1 in your file that is not allowed , you only can have one Header 1

**Comment by rugiraprince** [comment]
hey @samirm00 in had changed everything but now  i have to  make change to a file normally i am not suppose to change ? what can i do ?

**Comment by bermarte** [comment]
You need to run the npm scripts you find in package.json.
When adding files, please add one file at a time and avoid this:

`npm add .`

use this instead

`npm add <filename>`

You have changed also other files of the repo.

**Comment by bermarte** [comment]
> had changed everything but now i have to make change to a file normally i am not suppose to change ? what can i do ?

The best strategy is to switch to your branch and merge the files you changed from the main branch to your branch; it's like copying the files from a location to another.

`git merge package.json, file2, file3`

If you want we can do it together tomorrow.

**Comment by bermarte** [comment]
The best way to copy a file from main to your branch is to merge that file in your branch, tomorrow I can help you, just tag me on Slack.

```
git checkout <your_branch>
git merge <file_to_be_copied>
```

**Comment by bermarte** [comment]
The texts of your commits are not informative, they don't describe what you did. We will have a look at it together.

**Review by bermarte — CHANGES_REQUESTED** [review]
As I told you there are several little problems. We can have a look at it together.

**Comment by bermarte** [comment]
@rugiraprince You should always interact with the coaches, please leave feedback.

**Comment by rugiraprince** [comment]
@bermarte i just came from work now i read all your message and i realise  i had been using some wrong command that why i  was trying to delete the pull request so i can start from zero

**Comment by rugiraprince** [comment]
@bermarte is it ok can i delete the pull request and branch?

**Pull request closed without merging**
